import type { Metadata } from "next";
import { Geist, Geist_Mono, Orbitron } from "next/font/google";
import "./globals.css";
import Providers from "@/components/providers/session-provider";
import Footer from "@/components/footer";
import PageLoader from "@/components/ui/page-loader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap",
  preload: true,
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap",
  preload: false, // Не критичный шрифт
});

const orbitron = Orbitron({
  variable: "--font-orbitron",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
  display: "swap",
  preload: true, // Критичный для заголовков
});

export const metadata: Metadata = {
  title: "Консталтинг под ключ",
  description: "Generated by extremeitsolutions.ru",
  openGraph: {
    title: "Консталтинг под ключ",
    description: "Generated by extremeitsolutions.ru",
    type: "website",
  },
  twitter: {
    card: "summary",
    title: "Консталтинг под ключ",
    description: "Generated by extremeitsolutions.ru",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${orbitron.variable} antialiased`}
      >
        <PageLoader />
        <Providers>
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
